### ISSUE TITLE
request for the data

### ISSUE THREAD

**Issue by HRezaeiM** [shaoxiongji/sw-detection#1]
Hi, 
I was wondering about the data you have used for this work. I want to work on this issue on twitter data. I have noticed after running the scripts that the data files are not available. 
how can I get the data you tried your code on and see it running?
Thanks in advance

**Comment by maddigibiter** [comment]
@HRezaeiM you need to refer to this link https://www.reddit.com/r/datasets/comments/3bxlg7/i_have_every_publicly_available_reddit_comment/

**Comment by HRezaeiM** [comment]
So you don't have a tweet data its just Reddit? because in the Readme of the repository you have mentioned you worked 

> Twitter dataset has totally 10k tweets

**Comment by maddigibiter** [comment]
Well, its not my repo, just referring to links in documentation

**Comment by HRezaeiM** [comment]
> Well, its not my repo, just referring to links in documentation

Oh yea! I am sorry :D I thought you r the repo owner :D tnx btw :)

**Comment by shaoxiongji** [comment]
@HRezaeiM The dataset is available by request. For details, please refer to our paper. [Supervised Learning for Suicidal Ideation Detection in Online User Content](https://www.hindawi.com/journals/complexity/2018/6157249/abs/)

**Comment by shaoxiongji** [comment]
This dataset is not available any longer.
